services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/ver/lib/postgresql/data

volumes:
  pgdata: {}